[[liblsl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aab3557f7a66975a0bbc42e52f40b71c81ae630f"
libc = "musl"
os = "linux"

    [[liblsl.download]]
    sha256 = "8f55d5fa3da2e36b177bebb46ae73c9d04e7f6d04b639bfaf94fc23923f9f1ac"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.aarch64-linux-musl-cxx03.tar.gz"
[[liblsl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a913f7f22888ceabe98d2593419ee56fdb43dcc"
libc = "musl"
os = "linux"

    [[liblsl.download]]
    sha256 = "16d2fb958ebcd1f5cb12f9bf6c0a3ec1ef21b27e17c30d10a4c937cb9c2c3a25"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.aarch64-linux-musl-cxx11.tar.gz"
[[liblsl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c99507f2f087f2eaf4dde3c9bf5ef6f67338e76f"
libc = "musl"
os = "linux"

    [[liblsl.download]]
    sha256 = "f97c5d7054ebe12e2260341f3674e65b6779d6d1a2d0cd55b8487ff309ec0fd1"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f33c46ff2df01e74f848e6c7c346ab4277ae4874"
os = "windows"

    [[liblsl.download]]
    sha256 = "be1241b323cc3965b8c1f917ed9e454b08ef104b9c84de077d35c02111537673"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[liblsl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "213ee104a855844359d87243c6dac022e6116ca7"
libc = "musl"
os = "linux"

    [[liblsl.download]]
    sha256 = "d0c567780e9d7a7f50e24655f310b0c53d384d6f91efd7608eb37824a01f7345"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.i686-linux-musl-cxx11.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "740bdcbd0278206cb1e2679be9e4c796b1c918db"
libc = "musl"
os = "linux"

    [[liblsl.download]]
    sha256 = "bacda1c4009bf75eb31434501d53bc632133a3a91660b28d27a7c6048f76e52b"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-linux-musl-cxx11.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45276b880a4f18f3e6dbf379f2929ff1e5d20ff5"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "7259b971d7fd440f918ac082f60c3e83b02e18d925e3f44a12f2633b23eec4b1"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-linux-gnu-cxx03.tar.gz"
[[liblsl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c783b81c1dd8e74fe8c50f811fbbd68c4d7aa3ba"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "6c379d42fa6be136a03e7185afe385ba25287f6b2ea0b319b1b6791f8b8b0e52"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.i686-linux-gnu-cxx03.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc24fbb347f7dc92d2e20d8ce114a93f97707f45"
os = "macos"

    [[liblsl.download]]
    sha256 = "b26575c44853353243e9962a1620cd30c1ca9590f3a92c4aba73daf3f9d95e53"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[liblsl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08d866cfaded7c4111e40a037f14825a68866a4d"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "b9c7d77d7fe0e21aa16062184544eeac226b9d255033b5ec6fb7f4b97189fab2"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.i686-linux-gnu-cxx11.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86849fa8a677654680a7fed5ce6f2616c9425f7a"
os = "windows"

    [[liblsl.download]]
    sha256 = "19da72b57307290a206d684cf24f53be487b3c1f17ed9690a44eb89c4e95c65a"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb99dd8ea2331f908ce392687490fa15065b6f81"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "5cc53fa689c0ffe756de3d20448bd01a9a9654e4b7954017c598f93faf7e341f"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-linux-gnu-cxx11.tar.gz"
[[liblsl]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad9decef53e1aca27bdb7440a1409a22aecfafdf"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "21d6a4467f76dc91ded1aab32b692e4bed4336ad75f38601bfb4c38762ec378d"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[liblsl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75c80591a5375443911cad4af86f39be800254e2"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "388d26e791dc7ef6b1e99e56f24db8b0c6b198b97e0cfe0905a19566b5d18b82"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.aarch64-linux-gnu-cxx11.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "892e9b20cff2c2106fa0413d6bc30a192e135992"
libc = "musl"
os = "linux"

    [[liblsl.download]]
    sha256 = "bef52355fa83f935e6a30f52ebb46ed9d230d2a646cb0a15d31c48435eb0c373"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-linux-musl-cxx03.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efebb1b1625ed118d941b63aa4b99b2e511a4faf"
os = "macos"

    [[liblsl.download]]
    sha256 = "69973cd166704ba1d109065320cadbe00a3050dc1c184275369c5313d92f8a1f"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25dfc38654e01e53052386cdce868cb3eb1e0677"
os = "freebsd"

    [[liblsl.download]]
    sha256 = "18a04ddb05c5e3c3fd2c6bb2daa9d35224b1c1863aeb1a81dfa0f002715c421b"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[liblsl]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "861b59505bd62feec3da856fa239dc57fc4663fd"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "a9dfd55173df71eac865ff7576154fd9cddd20197a99bf8d9b25256623ea3e3c"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[liblsl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25252ba0593b041d42578cc95debe04b17933948"
os = "windows"

    [[liblsl.download]]
    sha256 = "be4ee2bddd6ee86d435414e9cb7f5ec93af6aa87fda48494cb56c7f0db804a20"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.i686-w64-mingw32-cxx03.tar.gz"
[[liblsl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "033d8dab52ca2362be5acb8d85e0b6895da18327"
os = "windows"

    [[liblsl.download]]
    sha256 = "66e053ea04b2a00b0d882dddc5e0b6595d88f75f5502c7b79e2a08e8b396e920"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.i686-w64-mingw32-cxx11.tar.gz"
[[liblsl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56802094f932fdddbc98d803bca756d201a2d569"
libc = "musl"
os = "linux"

    [[liblsl.download]]
    sha256 = "5ca6a41900835ed77b85afabad267e8f437e7bfbf9802ab6d79650827cc72bbd"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[liblsl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "defda72ae3613d570cb88735f7e0ad0d0a32778f"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "3e87de680042f7a94cd4831e4e9ddb79cc146dca7dc82b5285a6db533fbcf6ef"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[liblsl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6ec5a93574cdd54e33acf514081a4c33803d4c9"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "2b7ffd1565b4f47f586f360d3241b8be12c165a02d0a5449930c59f571405c05"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.aarch64-linux-gnu-cxx03.tar.gz"
[[liblsl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6be3778bc3b3e1154ab9383eee83bc1f15d5f5e2"
libc = "glibc"
os = "linux"

    [[liblsl.download]]
    sha256 = "fe03cce43b21f30fec49d8d166c72841edd25c3cfc6d2e91a4feb8daa413d7d6"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[liblsl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3caa2f5a1a21f1d79753d1af27d950fb2e6c793"
os = "freebsd"

    [[liblsl.download]]
    sha256 = "f6b288d66aa0a252656e24c676b009c704ae1d3bdd54cae7244f6310e2f8fb7c"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[liblsl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae7212ecd87d447ad31db0d0c0a0f921b812956b"
libc = "musl"
os = "linux"

    [[liblsl.download]]
    sha256 = "8ffe1fd274903469062a95c3eea230b966328cb7ea2dfa1c82aa52343aaf48ba"
    url = "https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases/download/liblsl-v1.13.0+1/liblsl.v1.13.0.i686-linux-musl-cxx03.tar.gz"
